/* The tables must be listed in leaf-root order in regards to FK-PK relationship */
DROP TABLE IF EXISTS PENDING_CONFIRMATIONS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ANSWERS;
DROP TABLE IF EXISTS QUESTIONS;
DROP TABLE IF EXISTS CLUSTERS;


CREATE TABLE USERS (
    USER_ID    INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
    FIRST_NAME VARCHAR(25)			 NOT NULL,
    LAST_NAME	 VARCHAR(25)			 NOT NULL,
    USERNAME   VARCHAR(20)       NOT NULL,
    PASSWORD   CHAR(40)          NOT NULL,
    EMAIL_ADDR VARCHAR(100)      NOT NULL,
    IS_ACTIVE  TINYINT(1)        DEFAULT 0,
    PERMISSION INTEGER UNSIGNED NOT NULL DEFAULT 0,

    PRIMARY KEY (USER_ID)
)
ENGINE=InnoDB DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;

CREATE TABLE PENDING_CONFIRMATIONS (
    USER_ID       INTEGER UNSIGNED  NOT NULL,
    TOKEN         CHAR(10)          NOT NULL,
    CREATED_DATE  TIMESTAMP         DEFAULT  CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
)
ENGINE=InnoDB DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs;


CREATE TABLE CLUSTERS (
    ID         INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
    NAME       VARCHAR(50)       UNIQUE NOT NULL, 
    DESCRIPTION      VARCHAR(100),

    PRIMARY KEY (ID)
)
ENGINE=InnoDB DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;


CREATE TABLE QUESTIONS (
    ID         INTEGER UNSIGNED  NOT NULL  AUTO_INCREMENT,
    CLUSTER_ID         INTEGER UNSIGNED  NOT NULL,
    CONTENT      VARCHAR(500)       NOT NULL, 
    ADDITIONAL_INFO    TEXT NULL,

    PRIMARY KEY (ID),
    
    FOREIGN KEY (CLUSTER_ID)
        REFERENCES CLUSTERS(ID)
)
ENGINE=InnoDB DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;


CREATE TABLE ANSWERS (
    ID         				BIGINT UNSIGNED   NOT NULL  AUTO_INCREMENT,
    QUESTION_ID       INTEGER UNSIGNED  NOT NULL,
    CONTENT      			TEXT              NOT NULL,
    IS_CORRECT				TINYINT(1)        NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),

    FOREIGN KEY (QUESTION_ID)
        REFERENCES QUESTIONS(ID)
)
ENGINE=InnoDB DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCREMENT=0;
